config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'trips#index'
  get 'users/sign_up', to: 'users#new'
  resources :users, except:[:new]
  get '/trips/friends', to: 'trips#friends'
  resources :trips
  resources :friendships, except: [:index, :new, :edit, :update, :show]
  resources :events
  resources :comments, only: [:create, :edit, :update, :destroy]
  resources :images, only: [:new, :create, :show, :edit, :update, :destroy]


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'events/:id', to: "events#copy", as: "copy_event"
  # post 'events/:id/edit', to: "events#update"
  # get '/events/images/new', to: 'images#new', as: "new_event_image"
  get '/events/:id/images/new', to: 'images#new', as: "new_event_image"

  post 'trips/:id', to: "trips#copy", as: "copy_trip"
  # get '/trips/images/new', to: 'images#new', as: "new_trip_image"
  get '/trips/:id/images/new', to: 'images#new', as: "new_trip_image"

end

app/models/trip.rb
# == Schema Information
#
# Table name: trips
#
#  id         :integer          not null, primary key
#  name       :string
#  start_date :datetime
#  end_date   :datetime
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Trip < ApplicationRecord
  has_many :events
  has_many :comments, :dependent => :destroy
  belongs_to :user
  has_many :images, :dependent => :destroy

  before_destroy :clear_events




  def self.all_with_events
    # Store trip_ids from all Events that have one (!= nil)
    trip_ids = Event.where.not(trip_id: nil).pluck(:trip_id)
    # Find all of those trips from Trips table
    Trip.where(id: trip_ids)
  end

  def event_titles
    self.events.pluck(:title)
  end

  def event_ids=(ids)
    self.events << Event.where(id: ids)
    #events that are added to a trip (new or update), are set to that trips' on_wish_list status
    self.events.update(on_wish_list: self.on_wish_list)
    # self.events.each do |event|
    #   event.on_wish_list = self.on_wish_list
    # end
    #Old code for reference:
    # events_arr = ids.map do |id|
    #   Event.find(id)
    # end
    #
    # events_arr.each do |event|
    #   self.events << event
    # end
  end

  def featured_image
    self.images.find_by(featured: true)
  end

  def featured_image_url
    if featured_image
      return featured_image.url
    else
      return ""
    end
  end

  def copy
    Trip.new(
    name: self.name,
    start_date: nil,
    end_date: nil,
    on_wish_list: true
    )
  end

  def copy_events(current_user, new_trip)
    self.events.each {|e| e.copy.update(user_id: current_user.id, trip_id: new_trip.id)}
  end

  private

    def clear_events
      self.events.each do |event|
        event.destroy
      end
    end

end

app/models/type.rb
# == Schema Information
#
# Table name: types
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Type < ApplicationRecord
  has_many :events

  validates :name, uniqueness: true
  
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :copy, :destroy]
  before_action :require_user, only:[:new, :edit, :update, :friends]

  def new
    @events  = [] # DOnt ask.
    @addable_events = current_user.orphan_events + current_user.wish_list_events
    @trip = Trip.new
  end

  def create
    trip = Trip.new(trip_params)
    current_user.trips << trip
    if params[:image]
      new_image = Image.new(image_params)
      new_image.trip = trip
      new_image.user = current_user
      new_image.featured = true
      new_image.save
    end
    if trip.save
      flash[:success] = "Trip successfully created!"
      redirect_to trip_path(trip)
    else
      flash[:danger] = "Unable to create trip"
      @events = current_user.events
      @trip = Trip.new
      render 'new'
    end
  end

  def index
    @trips = Trip.all_with_events.order(created_at: :desc)
    @trips = Kaminari.paginate_array(@trips).page(params[:page]).per(10)
  end

  def show
    @comment = Comment.new
    @comments = @trip.comments
    @featured_image_url = @trip.featured_image_url
  end

  def edit
    if !user_match?
      flash[:danger] = "You can only edit your own trips."
      redirect_to request.referer
    else
      @events = @trip.events
      @addable_events = current_user.orphan_events + current_user.wish_list_events
      #store previous page so it can be linked back to after update
      session[:return_to] ||= request.referer
      end
  end

  def update
    @trip.events.clear
    if @trip.update(trip_params)
      # TODO below needs to change - there are still params[:image] even with no image
      if params[:image][:url].length > 0
        new_image = Image.new(image_params)
        new_image.trip = @trip
        new_image.user = current_user
        new_image.save
        flash[:success]= "Image successfully updated."
      end
      if !trip_params[:on_wish_list] && @trip.on_wish_list
        @trip.events.update(on_wish_list:false)
        update_and_remove_from_wish_list(@trip)
        flash[:success] = "Trip successfully updated."
      end
    else
      flash[:danger]= @trip.errors.full_messages[0]
      redirect_to request.referer
    end
    redirect_to trip_path(@trip)
  end

  def copy
    @new_trip = @trip.copy
    @new_trip.images.clear
    current_user.trips << @new_trip
    if @new_trip.save
      #copy events from original trip to the new trip (must do after save so there is a trip_id)
      @trip.copy_events(current_user, @new_trip)
      flash[:success] = "Trip successfully copied to wishlist"
      redirect_to user_path(current_user)
    else
      flash[:danger] = @new_event.errors.full_messages[0] + " Trip was unable to be created, please try again."
    end
  end

  def destroy
    if !user_match?
      flash[:danger] = "You can only delete your own trips."
      redirect_to request.referer
    else
      @trip.destroy
      flash[:success] = "Trip successfully deleted."
      redirect_to user_path(current_user)
    end
  end

  def friends
    @trips = current_user.friend_trips
    if @trips.size == 0 || !@trips
      flash[:info]= "Your friends have no trips yet. Go on an adventure together!"
    end
  end

  private

  def set_trip
    @trip = Trip.find(params[:id])
  end

  def trip_params
    params.require(:trip).permit(:name, :on_wish_list, event_ids:[])
  end

  def image_params
    params.require(:image).permit(:url, :title, :caption)
  end

  def user_match?
    current_user && @trip.user == current_user
  end

  def update_and_remove_from_wish_list(trip)
    if trip.update(on_wish_list: false)
      flash[:success] = "Trip successfully removed from wishlist."
    else
      flash[:danger] = event.errors.full_messages[0]
    end
  end

end

app/views/trips/_form.html.erb
<%= form_for @trip do |f| %>
<div class="container">


  <div class="row">

    <div class="col-md-6">

        <p><%= f.label :name %>  <%= f.text_field :name %></p>
        <h3> My Events </h3>
        <% @events.each do |event| %>
        <p><%= f.check_box :event_ids, {:multiple => true}, event.id, nil %>  <%= f.label event.title %></p>
        <% end %>

        <% @addable_events.each do |event| %>
        <p><%= f.check_box :event_ids, {:multiple => true}, event.id, nil %>  <%= f.label event.title %></p>
        <% end %>
        <p><%= link_to "Create New Event", new_event_path %></p>
        <p><%= f.check_box :on_wish_list, {:multiple => false}, true, false %> <%= f.label "Trip on Wish List" %></p>
        <hr>
    </div>

    <div class="col-md-6">
      <h4>Add a photo (optional)</h4>
      <%= fields_for :image do |i| %>
      <p><%= i.label :url, "Image URL (please host elsewhere)"  %>
      <%= i.text_field :url %></p>
      <p><%= i.label :title %><br>
      <%= i.text_field :title %></p>
      <p><%= i.label :caption %><br>
      <%= i.text_area :caption %></p>
      <% end %>
    </div>

    <p><%= f.submit %></p>
    <% end %>
  </div>
</div>

<% if @trip.images.count > 0 %>
<hr>
<h3>Trip Photos</h3>
<br>
<%= render partial: '/images/images', locals: {images: @trip.images} %>
<% end %>

app/views/trips/_trip.html.erb
<div class="jumbotron">
  <h1><%= link_to trip.name, trip_path(trip) %></h1>
  <p> Trip by: <%= link_to trip.user.user_name, user_path(trip.user) %></p>
  <p><%= image_tag trip.featured_image_url, class: "img-fluid" %></p>
  <% trip.events.each do |event| %>
      <h4><%= link_to event.title, event_path(event) %></h4>
      <p><%= event.review %></p>
      <% if !event.rating.nil? %>
        <p><%= event.rating %><%= " star".pluralize(event.rating) %></p>
      <% end %>
  <% end %>
  <% if trip.images.count > 0 %>
  <hr>
  <h3>Trip Photos</h3>
  <br>
  <%= render partial: '/images/images', locals: {images: trip.images} %>
  <% end %>
  <% if trip.user == current_user %>
    <p><%= link_to "Add trip photo", new_trip_image_path(trip.id) %></p>
    <!--  if trip not on wish list show edit and delete links -->
    <% if !trip.on_wish_list %>
      <span><%= link_to "Edit trip", edit_trip_path(trip)%></span>
      <span> | </span>
      <span><%= link_to "Delete", trip_path(trip), method: :delete, data: { confirm: 'Delete Trip and all associated events?' } %></span>
    <!--  if trip on wish list show edit or mark complete and delete links -->
    <% else %>
      <p><%= link_to "Edit or Mark Complete", edit_trip_path(trip) %> | <%= link_to "Delete", trip_path(trip), method: :delete, data: { confirm: 'Delete Event?' } %></p>
    <% end %>
  <% else %>
    <p><%= link_to "Add to Wishlist", copy_trip_path(trip.id), method: :post %></p>
  <% end %>
</div>

app/views/trips/code_for_after_on_wish_list.html.erb
<% if trip.user == current_user %>
  <!--  if trip not on wish list show edit and delete links -->
  <% if !trip.on_wish_list %>
    <p><%= link_to "Add trip photo", new_trip_image_path %></p>
    <span><%= link_to "Edit", edit_trip_path(trip)%></span>
    <span> | </span>
    <span><%= link_to "Delete", trip_path(trip), method: :delete, data: { confirm: 'Delete Trip and all associated events?' } %></span>
   <!-- if trip on wish list show edit or mark complete and delete links -->
  <% else %>
    <span><%= link_to "Edit or Mark Complete", edit_trip_path(trip)%></span>
    <span> | </span>
    <span><%= link_to "Delete", trip_path(trip), method: :delete, data: { confirm: 'Delete Trip and all associated events?' } %></span>
  <% end %>
<% else %>
    <p><%= link_to "Add to Wishlist", copy_trip_path(trip), method: :post %></p>
<% end %>

app/views/trips/edit.html.erb
<title>Edit trip - Pintrips</title>
<h2> Edit Trip </h2>
<%= render "form" %>

app/views/trips/friends.html.erb
<title>Friends' Trips - Pintrips</title>
<% @trips.each do |trip| %>
  <%= render partial: 'trip', locals: {trip: trip} %>
<% end %>

app/views/trips/index.html.erb
<title>Trips - Pintrips</title>
<%= paginate @trips %>
<% @trips.each do |trip| %>
  <%= render partial: 'trip', locals: {trip: trip} %>
<% end %>
<%= paginate @trips %>

app/views/trips/new.html.erb
<title>Make a Trip - Pintrips</title>
<h2> Make a Trip </h2>
<%= render "form" %>

app/views/trips/show.html.erb
<title><%= @trip.name %> - Pintrips</title>
<%= render partial: 'trip', locals: {trip: @trip} %>
<p><%= link_to "Back to all Trips", trips_path %> | <%= link_to "Add a comment", "#", id: "new_comment_link" %></p>
<hr>
<p><%= render partial: '/comments/new', locals: {comment: @comment, type: "trip", id: @trip.id} %></p>
<%= render partial: '/comments/show', locals: {comments: @comments} %>

<script type="text/javascript">

// Store the comment form html, then hide the form


commentFormStore = $('.new_comment').html()
$('.new_comment').html("")


debugger;
$('#new_comment_link').on('click', commentFormStore, function(event) {
  event.preventDefault();
  $('.new_comment').html(event.data) // Re-create the form
  $('.new_comment').style.display = ""  // Show the form

}, true)

</script>