config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'trips#index'
  get 'users/sign_up', to: 'users#new'
  resources :users, except:[:new]
  get '/trips/friends', to: 'trips#friends'
  resources :trips
  resources :friendships, except: [:index, :new, :edit, :update, :show]
  resources :events
  resources :comments, only: [:create, :edit, :update, :destroy]
  resources :images, only: [:new, :create, :show, :edit, :update, :destroy]


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'events/:id', to: "events#copy", as: "copy_event"
  # post 'events/:id/edit', to: "events#update"
  # get '/events/images/new', to: 'images#new', as: "new_event_image"
  get '/events/:id/images/new', to: 'images#new', as: "new_event_image"

  post 'trips/:id', to: "trips#copy", as: "copy_trip"
  # get '/trips/images/new', to: 'images#new', as: "new_trip_image"
  get '/trips/:id/images/new', to: 'images#new', as: "new_trip_image"

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  content    :text
#  user_id    :integer
#  trip_id    :integer
#  event_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :trip, optional: true
  belongs_to :event, optional: true
  validate :event_or_user


  def event_or_user
    if !self.trip && !self.event
      #Add error to comment.
      errors[:base] << "Comment must be associated with either a trip or an event"
    end
  end

  def trip_or_event

  end

  def trip_or_event=(thing)
  end

end

app/controllers/comments_controller.rb
class CommentsController <ApplicationController

  before_action :set_comment, only: [:edit, :update, :destroy]

  def create
    new_comment = Comment.new(comment_params)
    new_comment.user = current_user
    new_comment.save
    if params[:trip_id]
      trip_id = params[:trip_id].keys[0].to_i  #  params given to us by hidden_field.  ugghh
      Trip.find(trip_id).comments << new_comment
      redirect_to trip_path(trip_id)
    end
    if params[:event_id]
      event_id = params[:event_id].keys[0].to_i
      Event.find(event_id).comments << new_comment
      redirect_to event_path(event_id)
    end
  end

  def edit
    if !user_match?
      flash[:danger] = "You can only edit your own comments."
      redirect_to request.referer
    else
    #store previous page so it can be linked back to after update
    session[:return_to] ||= request.referer
    end
  end

  def update
    @comment.update(comment_params)
    flash[:success]= "Comment successfully updated."
    redirect_to session.delete(:return_to)
  end

  def destroy
    if !user_match?
      flash[:danger] = "You can only delete your own comments."
      redirect_to request.referer

    else
      @comment.destroy
      flash[:success]= "Comment successfully deleted."
      redirect_to request.referer
    end
  end

  private

    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:content)
    end

    def user_match?
      current_user && @comment.user == current_user
    end

end

app/views/comments/_new.html.erb
<%= form_for comment do |f| %>
<p><%= f.label "Enter comment" %></p>
<p><%= f.text_area :content %></p>
  <% if type == "trip" %>
    <%= hidden_field(:trip_id, id) %>
  <% elsif type == "event" %>
    <%= hidden_field(:event_id, id) %>
  <% end %>
<% if logged_in? %>
  <%= f.submit class: "btn btn-primary" %>
<% else %>
  <%= f.submit class: "btn btn-primary", data: { confirm: 'Log in or sign up to post a comment!' } %>
<% end %>
<% end %>
<script type="text/javascript">

  // let comment_form = document.querySelector('.new_comment')
  document.querySelector('.new_comment').style.display = "none"

</script>

app/views/comments/_show.html.erb
<% comments.each do |c| %>
  <div style="background-color: #f3f3f3">
    <p><%= link_to c.user.user_name, user_path(c.user) %> commented at <%= c.created_at.to_date %></p>
    <p><%= c.content %></p>
    <% if c.user == current_user %>
      <span><%= link_to "Edit", edit_comment_path(c)%></span>
      <span> | </span>
      <span><%= link_to "Delete", comment_path(c), method: :delete, data: { confirm: 'Delete Comment?' } %></span>
    <% end %>
  </div>
  <hr>
<% end %>

app/views/comments/edit.html.erb
<title>Edit comment - Pintrips</title>
<h3>Edit Comment</h3>
<%= form_for @comment do |f| %>
<%= f.text_area :content %>
<br>
<%= f.submit %>
<% end %>