config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'trips#index'
  get 'users/sign_up', to: 'users#new'
  resources :users, except:[:new]
  get '/trips/friends', to: 'trips#friends'
  resources :trips
  resources :friendships, except: [:index, :new, :edit, :update, :show]
  resources :events
  resources :comments, only: [:create, :edit, :update, :destroy]
  resources :images, only: [:new, :create, :show, :edit, :update, :destroy]


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'events/:id', to: "events#copy", as: "copy_event"
  # post 'events/:id/edit', to: "events#update"
  # get '/events/images/new', to: 'images#new', as: "new_event_image"
  get '/events/:id/images/new', to: 'images#new', as: "new_event_image"

  post 'trips/:id', to: "trips#copy", as: "copy_trip"
  # get '/trips/images/new', to: 'images#new', as: "new_trip_image"
  get '/trips/:id/images/new', to: 'images#new', as: "new_trip_image"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  user_name       :string
#  password_digest :string
#  first_name      :string
#  last_name       :string
#  email           :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  has_many :friendships, :dependent => :destroy
  has_many :friends, through: :friendships
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id", :dependent => :destroy
  has_many :inverse_friends, through: :inverse_friendships, source: :user, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :events, :dependent => :destroy
  has_many :trips, :dependent => :destroy
  has_many :locations, through: :events
  has_many :images, :dependent => :destroy
  has_one :profile_image, class_name: "Image", :dependent => :destroy
  accepts_nested_attributes_for :profile_image

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  validates :user_name, presence: true,
                        uniqueness: {case_sensitive: false},
                        length: {minimum:3, maximum: 25}

  has_secure_password

  # TODO DELETE once all uses have been removed in views
  # def is?(object)
  #   # Used primarily to see if the user is the current_user on view pages
  #   self == object
  # end

  def wish_list_header
    "Wishlist:"
  end

  def trips_header
      "Trips"
  end

  def events_header
    case self.orphan_events.count
    when 0 then ""
    else
      "Events"
    end
  end

  def wish_list_trips_header
    case self.wish_list_trips.count
    when 0 then ""
    else
      "Trips"
    end
  end

  def wish_list_events_header
    case self.wish_list_events.count
    when 0 then ""
    else
      "Events"
    end
  end


  def image_params

  end

  def image_params=(params)

  end

  def completed_trips
    self.trips.where(on_wish_list: false)
  end

  def completed_events
    self.events.where(on_wish_list: false)
  end

  def orphan_events
    #old code for reference
    # self.events.select {|event| event.is_orphan? && event.on_wish_list == false}
    self.events.where(on_wish_list: false, trip_id: nil)
  end

  def wish_list_trips
    self.trips.where(on_wish_list: true)
  end

  def wish_list_events
    self.events.where(on_wish_list: true, trip_id: nil)
  end

  def friend_trips
    #get ids of friends
    friend_ids = self.friends.pluck(:id)
    #find trips that have user_id that matches a friend_id
    Trip.where(user_id: friend_ids)
    #old code for reference
    # self.friends.collect {|friend| friend.trips}.flatten
  end

  def profile_image_url

  end

  def profile_image_url=(url)
    self.profile_image = Image.new(url: url)
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :show]

  def index
    @users = User.all
  end

  def new
    if current_user
      redirect_to user_path(current_user)
    end
    @profile_image = Image.new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if params[:profile_image]
      @image = Image.new(image_params)
      @user.profile_image = @image
      @image.save
    end
    if @user.save
      flash[:success] = "Welcome to PinTrips #{@user.user_name}!"
      session[:user_id] = @user.id
      #Maybe hange this path once we have a better page to redirect them to?
      redirect_to user_path(@user)
    else
      flash[:alert] = @user.errors.full_messages[0]
      render 'new'
    end
  end

  def edit
    
  end

  def update
    if params[:profile_image]
      @image = Image.new(image_params)
      @user.profile_image = @image
      @image.save
    end
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def show
    @trips = @user.completed_trips
    @orphan_events = @user.orphan_events
    @wish_list_trips = @user.wish_list_trips
    @wish_list_events = @user.wish_list_events
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:user_name, :email, :password, :first_name, :last_name, :profile_image_url)
  end

  def image_params
    params.require(:profile_image).permit(:url, :title, :caption)
  end
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
<div class="row">
    <div class="col-md-6">

      <p>
        <%= f.label :user_name %>:
        <%= f.text_field :user_name %>
      </p>
      <p>
        <%= f.label :email %>:
        <%= f.email_field :email %>
      </p>
      <p>
        <%= f.label :password %>:
        <%= f.password_field :password %>
      </p>
      <p>
        <%= f.label :password_confirmation %>:
        <%= f.password_field :password_confirmation %>
      </p>
      <p>
        <%= f.label :first_name %>:
        <%= f.text_field :first_name %>
      </p>
      <p>
        <%= f.label :last_name %>:
        <%= f.text_field :last_name %>
      </p>

    </div>

    <div class="col-md-6">
        <h4>Add a photo (optional)</h4>
        <%= fields_for :profile_image do |i| %>
          <p><%= i.label :url, "Image URL (please host elsewhere)"  %>
          <%= i.text_field :url %></p>
          <p><%= i.label :title %><br>
          <%= i.text_field :title %></p>
          <p><%= i.label :caption %><br>
          <%= i.text_area :caption %></p>
        <% end %>


    </div>
    <p><%= f.submit %></p>

</div>
<% end %>

app/views/users/_map.html.erb
<style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 20em;
      }

</style>
<% event = user.events.first %>
<div id="map"></div>
<script>

  function initMap() {


    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 2,
      center: {lat: 40.705255, lng: -74.013973},
    });
    <% user.completed_events.each do |event| %>

      var myLatLng = {lat: <%= event.location.lat %>, lng: <%= event.location.long %>};
      var contentString = '<%= event.title %>'+
                          '<br><%= event.location.name %>'

      var infowindow<%= event.location.id %> = new google.maps.InfoWindow({
          content: contentString,
          position: myLatLng
        });

      var marker<%= event.location.id %> = new google.maps.Marker({
        position: myLatLng,
        map: map,
        title: "<%= event.title %>"
      });

        marker<%= event.location.id %>.addListener('click', function() {
          infowindow<%= event.location.id %>.open(map, marker<%= event.location.id %>);
        });
        <% puts event.location.id %>

    <% end %>
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBsxlU4Q04vn0Qnf2gTGhFBFsBxo04xZ-w&callback=initMap"
async defer></script>

app/views/users/album.html.erb
<div class="row">
  <% @user.trips.each do |trip| %>
    <% trip.images.each do |img| %>
      <div class="card">
        <a href="<%= image_path(img) %>"><img class="img-fluid" width="280" src="<%= img.url %>" alt="<%= img.title %>"></a>
        <p class="card-text"><%= img.caption %></p>
      </div>
      <% trip.events.each do |event| %>
        <% event.images.each do |img| %>
          <div class="card">
            <a href="<%= image_path(img) %>"><img class="img-fluid" width="280" src="<%= img.url %>" alt="<%= img.title %>"></a>
            <p class="card-text"><%= img.caption %></p>
          </div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>

</div>

app/views/users/edit.html.erb
<title>Edit profile - Pintrips</title>
<%= render "form" %>

app/views/users/index.html.erb
<title>Pintrips</title>
<h1>User List</h1>

<div id="users">
<% @users.each do |user| %>
  <div class="user">
    <p>
      <strong><%= link_to user.user_name, user_path(user) %></strong>
      <% if logged_in? %>
      <%= puts "You" if (user == current_user) %>
      <%= puts "should NOT have add friend link for #{user.user_name}" if Friendship.between(user, current_user) %>

      <%# byebug %>
        <% if !(user == current_user) && !Friendship.between(current_user, user)%>
          (<%= link_to "add friend", friendships_path(friend_id: user), method: :post%>)
        <% end %>
      <% end %>
      <div class="clear"></div>
    </p>
  </div>
<% end %>
</div>

app/views/users/new.html.erb
<title>New user - Pintrips</title>
<%= render "form" %>

app/views/users/show.html.erb
<title><%= @user.user_name %> - Pintrips</title>
<div class="row">
  <div class="col-md-8">
    <%= render partial: 'map', locals: {user: @user} %>
  </br>
    <center><h3><%= @user.trips_header %></h3></center>
    <% if @user.trips.empty? %>
      <% if @user == current_user %>
        <center><p> No trips yet.  <%= link_to "Create a trip", new_trip_path %> and tell everyone about your adventure!</p></center>
        <% else %>
        <center><p><%= @user.user_name %> hasn't created any trips yet.</p></center>
      <% end %>
    <% end %>

    <% @trips.each do |trip| %>
      <div class="jumbotron">
        <%= render partial: 'trips/trip', locals: {trip: trip, featured_image_url: trip.featured_image_url} %>
      </div>
    <% end %>
    <% if current_user && current_user == @user %>
      <p><%= link_to "Create new trip", new_trip_path unless @user.trips.empty? %></p>
    <% end %>
    <hr>

    <center><h3><%= @user.events_header %></h3></center>

    <% if @user.events.empty? && @user.trips.empty? %>
      <% if @user == current_user %>
        <center><p> No events yet.  <%= link_to "Create an event", new_event_path %> and tell everyone about your adventure!</p></center>
        <% else %>
        <center><p><%= @user.user_name %> hasn't created any events yet.</p></center>
      <% end %>
    <% end %>

    <% @orphan_events.each do |event| %>
      <%= render partial: "/events/event", locals: {event: event} %>
    <% end %>

    <br>
    <% if current_user && current_user == @user %>
      <%= link_to "Create new event", new_event_path %>
    <% end %>
    <hr>

    <!-- WISH LIST SECTION -->
    <center><h2><%= @user.wish_list_header %></h2></center>

    <% if @user.wish_list_trips.empty? && @user.wish_list_events.empty? %>
      <% if @user == current_user %>
        <center><p> You haven't added any trips or events to your wishlist.  <%= link_to "Browse trips", trips_path %> or <%= link_to "events,", events_path %> and find one that inspires you! </p></center>
        <% else %>
        <center><p>No trips or events on <%= @user.user_name %>'s wishlist.</p></center>
      <% end %>
    <% end %>



    <!-- Trips Wish List -->
    <center><h3><%= @user.wish_list_trips_header %></h3></center>


    <% @wish_list_trips.each do |trip| %>
      <%= render partial: "/trips/trip", locals: {trip: trip} %>
    <% end %>

    <!--  Events Wish List -->
    <center><h3><%= @user.wish_list_events_header %></h3></center>
    <% @wish_list_events.each do |event| %>
      <%= render partial: "/events/event", locals: {event: event} %>
    <% end %>

  </div>
  <div class="col-md-4">
    <h1><%= @user.user_name %></h1>
    <% if logged_in? %>
      <% if current_user != @user && !Friendship.between(current_user, @user) %>
        <p>(<%= link_to "add friend", friendships_path(friend_id: @user), method: :post%>)</p>
      <% end %>
    <% end %>
    <% if @user.profile_image %>
      <a href="<%= image_path(@user.profile_image) %>"><img class="img-fluid" width="280" src="<%= @user.profile_image.url %>" alt="<%= @user.profile_image.title %>" style="border-radius: 50%"></a>
    <% end %>
    <p><%= @user.first_name %> <%= @user.last_name %></p>
    <p><%= @user.email %></p>

    <% if @user == current_user %>
    <h3>My Friends:</h3>
    <% else %>
    <h3><%= @user.first_name %>'s Friends</h3>
    <% end %>


    <% @user.friendships.each do |friendship| %>
      <li>
        <%=link_to friendship.friend.user_name, user_path(friendship.friend.id)%>
        <% if current_user %>
          (<%=link_to "remove", friendship_path(friendship.friend.id), :method => :delete %>)
        <% end %>
      </li>
    <% end %>

    <% if @user == current_user %>
      <p><%= link_to "Find Friends", users_path %></p>
    <% end %>

    <% if @user == current_user %>
    <h3>Added me:</h3>
    <% else %>
    <h3>Added <%= @user.first_name %>:</h3>
    <% end %>

    <% @user.inverse_friends.each do |friend| %>
    <li>
      <%= link_to friend.user_name, user_path(friend) %>
      <% if current_user == @user && !Friendship.between(current_user, friend) %>
        (<%= link_to "add friend", friendships_path(friend_id: friend), method: :post%>)
      <% end %>
    </li>
    <% end %>
  </div>
</div>