config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'trips#index'
  get 'users/sign_up', to: 'users#new'
  resources :users, except:[:new]
  get '/trips/friends', to: 'trips#friends'
  resources :trips
  resources :friendships, except: [:index, :new, :edit, :update, :show]
  resources :events
  resources :comments, only: [:create, :edit, :update, :destroy]
  resources :images, only: [:new, :create, :show, :edit, :update, :destroy]


  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'events/:id', to: "events#copy", as: "copy_event"
  # post 'events/:id/edit', to: "events#update"
  # get '/events/images/new', to: 'images#new', as: "new_event_image"
  get '/events/:id/images/new', to: 'images#new', as: "new_event_image"

  post 'trips/:id', to: "trips#copy", as: "copy_trip"
  # get '/trips/images/new', to: 'images#new', as: "new_trip_image"
  get '/trips/:id/images/new', to: 'images#new', as: "new_trip_image"

end

app/views/layouts/_nav.html.erb
<!--Navbar-->
<nav class="navbar navbar-md navbar-dark bg-primary">
  <div class="container">
    <% if logged_in? %>
      <a class="nav-link dropdown-toggle" href="<%= user_path(current_user) %>" id="navbarDropdownMenuLink" style="color: #ffffff" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <%= "#{current_user.user_name}" %>
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        <%= link_to "View Profile", user_path(current_user.id), class: 'dropdown-item' %>
        <%= link_to "Edit Profile", edit_user_path(current_user.id), class: 'dropdown-item' %>
        <%= link_to "Logout", logout_path, method: :delete, class: 'dropdown-item' %>
      </div>
      <%= link_to "Friends' Trips", trips_friends_path, class: 'nav-link', style: 'color: #ffffff;' %>
    <% else %>
      <%= link_to "Log In", login_path, class: 'nav-link', style: 'color: #ffffff;' %>
      <%= link_to "Sign Up", users_sign_up_path, class: 'nav-link', style: 'color: #ffffff;' %>
    <% end %>
    <%= link_to "All Trips", trips_path, style: 'color: #ffffff;' %>
    <%= link_to "All Events", events_path, class: 'nav-link', style: 'color: #ffffff;' %>
    <% if logged_in? %>
      <a class="navbar-brand" href="/users/<%= current_user.id %>">
        <img src="https://cdn4.iconfinder.com/data/icons/flatified/512/map.png" width="30" height="30" class="d-inline-block align-top" alt="">
        <strong>Pintrips</strong>
      </a>
    <% else %>
    <a class="navbar-brand" href="/trips">
      <img src="https://cdn4.iconfinder.com/data/icons/flatified/512/map.png" width="30" height="30" class="d-inline-block align-top" alt="">
      <strong>Pintrips</strong>
    </a>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- <title>Pintrips</title> -->
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
    <style >
      body { background-color: powderblue; background-image: url("/topography.png");}
    </style>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>

  <body>

    <div class="container" >
      <%= render '/layouts/nav' %>
    </br>
      <!--  Flash messages -->
      <% flash.each do |name, msg|%>
        <div class = "alert alert-<%= name %> alert-dismissable">
          <p> <%=  msg  %></p>
        </div>
      </br>
      <% end %>
      <!-- Log out and View Profile Links TODO: put these in a div or divs for css later-->
      <!-- <% if logged_in?%>
        <%= "Welcome #{current_user.user_name}! Not you? "%>
        <%= link_to "Log out", logout_path, method: :delete %>
        <label> | </label>
        <%= link_to "View Profile", users_sign_up_path %>
      <% end %> -->
      <%= yield %>
      <div class="mastfoot">
        <div class="inner">
          <p>&copy; 2017 | <b> CJD @ Flatiron </b> All Rights Reserved</p>
        </div>
      </div>
  </div>
  </body>
</html>

app/views/layouts/tempnav.html.erb
<!--Navbar-->
<nav class="navbar navbar-md navbar-dark bg-primary">
  <div class="container">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav1" aria-controls="navbarNav1" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <% if logged_in? %>
      <a class="navbar-brand" href="/users/<%= current_user.id %>">
        <img src="https://cdn4.iconfinder.com/data/icons/flatified/512/map.png" width="30" height="30" class="d-inline-block align-top" alt="">
        <strong>Pintrips</strong>
      </a>
    <% else %>
    <a class="navbar-brand" href="/trips">
      <img src="https://cdn4.iconfinder.com/data/icons/flatified/512/map.png" width="30" height="30" class="d-inline-block align-top" alt="">
      <strong>Pintrips</strong>
    </a>
    <% end %>
      <div class="collapse navbar-collapse" id="navbarNav1">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <%= link_to "All Trips", trips_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
              <%= link_to "All Events", events_path, class: 'nav-link' %>
            </li>
            <% if logged_in? %>
              <li class="nav-item">
                <%= link_to "Friends' Trips", trips_friends_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                  <%= link_to "View Profile", user_path(current_user.id), class: 'nav-link' %>
              </li>
              <li class="nav-item">
                  <%= link_to "Edit Profile", edit_user_path(current_user.id), class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to "Logout", logout_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                  <%= link_to "Log In", login_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                  <%= link_to "Sign Up", users_sign_up_path, class: 'nav-link' %>
              </li>
            <% end %>
        </ul>
      </div>
  </div>
</nav>